import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Hamburgermenu(),
        ]),
      ),
    );
  }
}

class Hamburgermenu extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 284,
          height: 640,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 8,
                top: -13,
                child: Container(
                  width: 284,
                  height: 640,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 0,
                top: -2,
                child: Container(
                  width: 284,
                  height: 257,
                  decoration: BoxDecoration(color: const Color(0xFF30CBAF)),
                ),
              ),
              Positioned(
                left: 77,
                top: 184,
                child: Text(
                  'Rip Jakharia',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 22,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 277,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 30,
                  children: [
                    Container(
                      width: 32,
                      height: 32,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: NetworkImage("https://static.vecteezy.com/system/resources/previews/010/260/479/large_2x/default-avatar-profile-icon-of-social-media-user-in-clipart-style-vector.jpg"),
                          fit: BoxFit.contain,
                        ),
                      ),
                    ),
                    Text(
                      'Profile',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 22,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 20,
                top: 331,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 30,
                  children: [
                    Container(
                      width: 32,
                      height: 32,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: NetworkImage("https://th.bing.com/th/id/OIP.qIU7PPS6j4X6QI3Ybt6YxQHaHa?w=1000&h=1000&rs=1&pid=ImgDetMain"),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                    Text(
                      'Settings',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 22,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 24,
                top: 385,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 30,
                  children: [
                    Container(
                      width: 20,
                      height: 20,
                      clipBehavior: Clip.antiAlias,
                      decoration: BoxDecoration(),
                      child: Stack(),
                    ),
                    Text(
                      'QR Code',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 22,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 20,
                top: 439,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 30,
                  children: [
                    Container(
                      width: 27,
                      height: 30,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: NetworkImage("https://static-00.iconduck.com/assets.00/share-icon-2048x1911-60w04qpe.png"),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                    Text(
                      ' Share',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 22,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 82,
                top: 493,
                child: Container(
                  width: 104,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Dashboard',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 22,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 499,
                child: Container(
                  width: 21,
                  height: 18,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://th.bing.com/th/id/OIP.Y8dtN5ZwipTpf_-R4HynJgAAAA?rs=1&pid=ImgDetMain"),
                      fit: BoxFit.contain,
                    ),
                    shape: RoundedRectangleBorder(side: BorderSide(width: 2)),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 547,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 32,
                  children: [
                    Container(
                      width: 27,
                      height: 27,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: NetworkImage("https://static.vecteezy.com/system/resources/previews/020/839/751/original/logout-icon-for-web-ui-design-vector.jpg"),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                    Text(
                      'Log Out',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 22,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 76,
                top: 223,
                child: Text(
                  '5556 3324 xxxx',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 9,
                child: Container(
                  width: 175,
                  height: 175,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://static.vecteezy.com/system/resources/previews/010/260/479/large_2x/default-avatar-profile-icon-of-social-media-user-in-clipart-style-vector.jpg"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}